language: python
sudo: required
python:
    - "3.8"
services:
    - postgresql
    - redis-server
install:
    - bash bin/travis-build.bash
    - pip install coveralls
script: sh bin/travis-run.sh
after_success:
    - coveralls
